{
 "title": "OKD Cincinnati VALET",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "route",
    "query": "label_values(haproxy_backend_http_responses_total, route)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(status_class:http_requests_total:rate5m{route=\"$route\", service=\"okd-cincinnati\", component=\"cincinnati-policy-engine\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "SLOs",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "content": "Calculated over the last 28 days\n\n\n\n"
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "100 * component:availability:slo_ok_5m{route=\"$route\",job=\"cincinnati-policy-engine\",service=\"okd-cincinnati\",component=\"cincinnati-policy-engine\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Volume  - 5k r/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "sum(avg_over_time(status_class:http_requests_total:rate5m{route=\"$route\", service=\"okd-cincinnati\", component=\"cincinnati-policy-engine\"}[28d]))"
    }
   ]
  },
  {
   "title": "Availability - 95%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "avg_over_time(component:availability:slo_ok_5m{component=\"cincinnati-policy-engine\",job=\"cincinnati-policy-engine\",service=\"okd-cincinnati\"}[28d]) * 100"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "component:latency:p90_rate5m{job=\"cincinnati-policy-engine\",service=\"okd-cincinnati\",component=\"cincinnati-policy-engine\"}",
     "legendFormat": "p90 latency"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "100 * status_class_5xx:http_requests_total:ratio_rate5m{route=\"$route\", service=\"okd-cincinnati\",component=\"cincinnati-policy-engine\"}",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Latency - 95%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(component:latency:slo_ok_5m{component=\"cincinnati-policy-engine\",job=\"cincinnati-policy-engine\",service=\"okd-cincinnati\"}[28d]) * 100"
    }
   ]
  },
  {
   "title": "Errors  - 95%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "avg_over_time(component:errors:slo_ok_5m{component=\"cincinnati-policy-engine\",route=\"$route\",service=\"okd-cincinnati\"}[28d]) * 100"
    }
   ]
  }
 ]
}